Lesson 5-7 p3: test script
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #100
Opened 2019-04-07 15:50 UTC by a-vodka

Test script for character device
please look at screenshot

![image](https://user-images.githubusercontent.com/6401696/55686088-e6303a00-5965-11e9-90dc-6619df85468f.png)

2019-04-09 16:05 UTC, galkinletter commented
Makefile - Need  fix var for  /home/alex/Downloads/linux-5.0.7 and etc
Makefile -   Need fix  end of line  

chrdev.c - Fix indents. Different indents

2019-04-09 16:23 UTC, galkinletter requested changes
Need fix Makefile and chrdev.c 

See comment

2019-04-09 16:36 UTC, galkinletter commented
Makefile - Please, add empty line at the end of file

2019-04-10 06:00 UTC, galkinletter requested changes
Need fix

2019-04-10 06:00 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Makefile
> +	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
```suggestion
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
	
```

Makefile - Need fix end of line

2019-04-10 06:00 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/chrdev.c
> +MODULE_VERSION("0.1");
Need fix end of line

2019-04-10 06:00 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/test-chr-dev.sh
> +rmmod $MOD
```suggestion
rmmod $MOD

```

Need fix end of line

2019-04-10 13:48 UTC, oleg-h2o requested changes
Fix error handling.

2019-04-10 13:48 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/chrdev.c
> +    error = sysfs_create_file(example_kobject, &sysfs_attribute.attr);
Error handling is broken here.

2019-04-11 11:37 UTC, galkinletter requested changes
Please Fix error handling.

2019-04-12 21:46 UTC, a-vodka commented on 02-KernelModules_CharacterDevice/chrdev.c
> +    error = sysfs_create_file(example_kobject, &sysfs_attribute.attr);
@oleg-h2o 

> Error handling is broken here.
What is it mean?

2019-04-23 15:46 UTC, merged