Lesson 5-7 part 1:Chardev
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #101
Opened 2019-04-07 16:46 UTC by MrStamp

Implementation of simple module

2019-04-09 16:18 UTC, galkinletter commented
chrdev.c - static int count = 1;  Never used.

Please comment in  driver source.

2019-04-09 16:20 UTC, galkinletter requested changes
chrdev.c - static int count = 1; Never used.
Please comment in driver source.

2019-04-10 13:53 UTC, oleg-h2o requested changes
Plz fix. 
There are indentation problems in the file also.

2019-04-10 13:53 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/chrdev.c
> +    	if (error) {
Error handling is broken here.

2019-04-10 13:53 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/chrdev.c
> +module_param(count, int, S_IRUGO);
Unused parameter.

2019-04-11 12:15 UTC, galkinletter requested changes
Please fix:

- Error handling
- Code style
- Unused parameter

2019-04-11 12:15 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Makefile
> +	make -C $(BUILD_KERNEL) M=$(PWD) clean
Please add empty line at the end of file
```suggestion
	make -C $(BUILD_KERNEL) M=$(PWD) clean
	
```

2019-04-12 14:51 UTC, galkinletter requested changes
Please Check kernel code with checkpatch and cppcheck

2019-04-12 14:51 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/chrdev.c
> +  return single_open(file, dev_proc_show, NULL);
Please Check kernel code with checkpatch and cppcheck

2019-04-23 15:53 UTC, galkinletter commented
It can be seen that the work was done

2019-04-23 15:53 UTC, merged