Lesson 02: Implementing a character device
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #102
Opened 2019-04-07 20:08 UTC by connor41

* Implement character device driver, and control interfaces for this device
* Add script to test this device `test.sh`
* Add testing instruction `Testing.md`

2019-04-09 20:12 UTC, galkinletter requested changes
Need fixe code style

2019-04-09 20:12 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Makefile
> +endif
```suggestion
endif

```

Please add empty line at the end of file

2019-04-09 20:12 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/concdev.h
> +#endif
Plaese add empty line at the end of file

2019-04-09 20:12 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/concmod.c
> +module_exit(cmod_exit);
add empty line at the end of file

2019-04-09 20:12 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/proc_info.c
> +}
add empty line at the end of file

2019-04-09 20:12 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/proc_info.h
> +#endif
Please add empty line at the end of file

2019-04-09 20:12 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/sysfs_control.c
> +}
Please add empty line at the end of file

2019-04-09 20:12 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/sysfs_control.h
> +#endif
add empty line at the end of file

2019-04-09 20:12 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/test.sh
> +fi
Please add empty line at the end of file

2019-04-09 20:12 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/sysfs_control.c
> +static ssize_t sysfs_control_store(struct device *dev,
```suggestion
static ssize_t sysfs_control_store(struct device *dev,struct device_attribute *attr, const char *buf, size_t count)
```

Need fixe code style

2019-04-09 21:31 UTC, galkinletter requested changes
Need fix empty line at the end of file

2019-04-09 21:31 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Makefile
> +endif
add empty line at the end of file

2019-04-10 08:38 UTC, connor41 commented
![скрин](i.imgur.com/nafE5kt.png)

2019-04-10 08:44 UTC, connor41 commented
i.imgur.com/nafE5kt.png

2019-04-10 08:50 UTC, connor41 commented
![image](https://user-images.githubusercontent.com/29237312/55865326-cc217200-5b86-11e9-8f26-79be4bbd4625.png)

2019-04-10 14:00 UTC, oleg-h2o requested changes
Fix error handling.

2019-04-10 14:00 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/concdev.c
> +	fail:
Error handling is not just printing a message.
remove_proc_info() ?
unregister_chrdev_region(devno, count_dev) ?
cdev_del(cdev) ?
etc.

2019-04-11 12:25 UTC, galkinletter requested changes
Need fix last problem in  code style

2019-04-11 12:25 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/concdev.c
> +    dev_t dev = 0;
```suggestion
         dev_t dev = 0;
```
Please fix last problem in  code style

2019-04-11 15:27 UTC, galkinletter commented
Accepted!

2019-04-11 15:27 UTC, merged