Lesson 7 Part 2: /sys and /proc interfaces
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #107
Opened 2019-04-08 21:12 UTC by Noxybot

2019-04-09 19:54 UTC, galkinletter requested changes
Need fix code style

2019-04-09 19:54 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Create_device.h
> +}
add empty line at the end of file

2019-04-09 19:54 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Create_device.h
> +}
Create_device.h  it is bad name for *.h

2019-04-09 19:54 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Makefile
> +	$(MAKE) -C ${KDIR} M=$$PWD clean
Please, add empty line at the end of file

2019-04-09 19:54 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Makefile
> +KDIR := /home/eduard/Kernel_i386
PATH  need fix
like 
PATH := $(PATH):/my/dir

2019-04-09 19:54 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Memory_management.h
> +}
Please, add empty line at the end of file

2019-04-09 19:54 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Sys_interface.h
> +}
Please, add empty line at the end of file

2019-04-10 14:13 UTC, oleg-h2o requested changes
Plz move function implementations from .h files to .c

2019-04-10 14:13 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/Create_device.h
> +#pragma once
Header files in the Linux kernel are used for two purposes:
    1. to define interfaces between components of the kernel, and
    2. to define interfaces between the kernel and user space 
Plz put function implementations into .c files.

2019-04-20 14:39 UTC, closed without merging