Lesson 7 Part 3: Simple bash script for module testing
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #108
Opened 2019-04-08 22:42 UTC by Noxybot

2019-04-09 18:40 UTC, galkinletter requested changes
Need fix

2019-04-09 18:40 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Makefile
> +	$(MAKE) -C ${KDIR} M=$$PWD clean
```suggestion
	$(MAKE) -C ${KDIR} M=$$PWD clean
	
```

Please add empty line at the end of file

2019-04-09 18:51 UTC, galkinletter requested changes

2019-04-09 18:51 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/test_script.sh
> +PATH_TO_DRIVER="/home/user/char_driver/Character_driver.ko"
Need PATH like variables in makefile

2019-04-09 19:11 UTC, galkinletter requested changes
Need fix

2019-04-09 19:11 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Makefile
> +KDIR := /home/eduard/Kernel_i386
Need PATH like variables in makefile

2019-04-09 19:11 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Create_device.h
> +#pragma once
Using #pragma once should work on any modern compiler, but I don't see any reason not to use a standard #ifndef include guard. It works just fine. The one caveat is that GCC didn't support #pragma once before version 3.4.

2019-04-09 19:11 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Character_driver.c
> +module_exit(char_driver_exit);
Please, add empty line at the end of file

2019-04-09 19:11 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Create_device.h
> +}
Please, add empty line at the end of file

2019-04-09 19:11 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Memory_management.h
> +}
Please, add empty line at the end of file

2019-04-09 19:11 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Sys_interface.h
> +}
Please, add empty line at the end of file

2019-04-09 19:11 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/test_script.sh
> +rmmod Character_driver
Please, add empty line at the end of file

2019-04-11 16:09 UTC, galkinletter requested changes
Need fix 

Remove implementation. There must be a function declaration in *.h

2019-04-11 16:09 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/character_driver.c
> +module_exit(char_driver_exit);
```suggestion
module_exit(char_driver_exit);

```
Please, add empty line at the end of file

2019-04-11 16:09 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/device_creation.h
> +static struct file_operations my_fops = {
```suggestion

```
Remove implementation  a function . There must be a function declaration
Remove file_operation from .h

2019-04-12 15:17 UTC, oleg-h2o requested changes
Do handle errors, please

2019-04-12 15:17 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/character_driver.c
> +    alloc_chrdev_region(&dev, 0/*statring from minor number 0*/, NUMBER_OF_DEVICES, DEVICE_NAME); //ask kernel to allocate free major number
alloc_chrdev_region() returns 0 or error code.

2019-04-12 15:17 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/character_driver.c
> +    cdev_add(&my_dev, dev, 1);
cdev_add() returns a negative error code on failure.

2019-04-12 15:17 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/character_driver.c
> +    my_class = class_create(THIS_MODULE, "Char_driver");
There are no any error handling
if(IS_ERR(my_class)) ...

2019-04-20 14:39 UTC, closed without merging