Lesson05-07: Implement character device driver with procfs/sysfs interfaces
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #109
Opened 2019-04-09 09:01 UTC by yorkened

# Summary
This is my implementation of character device driver for text messaging between users. Such steps were followed during development:
- Created new Linux kernel module;
- Implemented read/write functions from file_operations struct;
- Provided buffer increase as a module parameter;
- Provided work only with ASCII strings;
- Implemented procfs interface to get information about current buffer size and capacity;
- Implemented sysfs interface for buffer clearance.
## Device driver testing scenario
1. Check if module is loaded and relevant device and interfaces exist.
2. Print information about initial buffer state from procfs inerface.
3. Write data to character device.
4. Check if info about written data available from procfs interface.
5. Read all data from character device.
6. Check if buffer is clear now.
7. Write data to device again and clear buffer with sysfs interface.
8. Try to write data blocks to character device from /dev/urandom to check if driver deny writing of non-ASCII strings.

2019-04-09 19:39 UTC, galkinletter requested changes
Makefile missing

2019-04-09 20:00 UTC, yorkened commented
@galkinletter, but there is no mentioning in task that makefile source is needed

2019-04-09 20:17 UTC, galkinletter commented
For all the following tasks, it should be the default

2019-04-09 20:20 UTC, yorkened commented
@galkinletter, so I just need to upload my makefile used during building of module?

2019-04-09 21:00 UTC, yorkened commented
Done. Makefile was added
@galkinletter please, review my request

2019-04-11 16:16 UTC, galkinletter requested changes
Please fix empty line at the end of file

2019-04-11 16:16 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/src/Makefile
> +	$(MAKE) -C $(BUILD_KERNEL) M=$(CURDIR) clean
Need Fix - add empty line at the end of file
```suggestion
	$(MAKE) -C $(BUILD_KERNEL) M=$(CURDIR) clean
	
```

2019-04-11 16:16 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/src/intercom.c
> +MODULE_VERSION("0.1");
add empty line at the end of file
```suggestion
MODULE_VERSION("0.1");

```

2019-04-11 16:16 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/test/devtest.sh
> +dd if=/dev/urandom of=$DEVICE bs=512 count=4
add empty line at the end of file

2019-04-11 16:18 UTC, galkinletter commented
Thank you for your attention to error handling.

2019-04-11 16:30 UTC, yorkened commented
@galkinletter sorry, but my sources already have newlines at the end of files. Github just trim them all for good-looking web view. On the other hand, if it was no newlines at the end of files, you will see following pop-up notification. And if you, for example, select "view file" for my makefile, you will see that there are 12 lines in file, but github shows only 11 of them.

![изображение](https://user-images.githubusercontent.com/22673773/55973991-5fde6580-5c8f-11e9-8027-e13a56b64477.png)

![изображение](https://user-images.githubusercontent.com/22673773/55974295-0296e400-5c90-11e9-9d77-2605b4208273.png)

2019-04-12 15:23 UTC, oleg-h2o requested changes
Now it's almost perfect, but a little fix is required

2019-04-12 15:23 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/src/intercom.c
> +	add_uevent_var(env, "DEVMODE=%#o", 0666);
if(add_uevent....)
    return -ENOMEM;

2019-04-14 10:51 UTC, yorkened commented
@oleg-h2o, fix is ready, please, make review.

2019-04-23 15:35 UTC, merged