Lesson 5-7 part 1: Driver
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #111
Opened 2019-04-09 20:31 UTC by vizhyk

I didn't describe read function  for proc and write for sys and it's not final version, but please check my code . Maybe You will find some misstakes.

2019-04-09 20:35 UTC, galkinletter requested changes
Need fix code style

Makefile missing

2019-04-09 20:35 UTC, galkinletter commented on chtest.c
> +module_exit(chtest_exit);
Please add empty line at the end of file

2019-04-09 20:36 UTC, galkinletter commented
Please push makefile also

2019-04-09 20:46 UTC, vizhyk commented
@galkinletter , Add Makefile

2019-04-09 20:56 UTC, galkinletter requested changes
Need fix makefile

2019-04-09 20:56 UTC, galkinletter commented on Makefile
>  	$(CC) $(Opt) -c ./Second.c -o ./Second.o
Makefile need for chtest.c

2019-04-09 21:22 UTC, galkinletter requested changes
Need fix Makefile

2019-04-11 09:20 UTC, vizhyk commented
@galkinletter  @oleg-h2o It's final version of char. driver. Please, review it.

2019-04-11 16:34 UTC, galkinletter requested changes
Please fix code style


check the code formatting

2019-04-11 16:34 UTC, galkinletter commented on chtest.c
> +static void __exit chtest_exit(void){
```suggestion
static void __exit chtest_exit(void)
{
```
Please fix Kernel code style

2019-04-11 16:34 UTC, galkinletter commented on chtest.c
> +sys_cleanup();       	         		    //sys_cleanup
```suggestion
 sys_cleanup();       	         		    //sys_cleanup	
```

Please fix code style also

2019-04-12 00:19 UTC, vizhyk commented
@galkinletter  @oleg-h2o Fixed code style. Please, check it again.

2019-04-12 15:29 UTC, oleg-h2o requested changes
Do read the CodeStyle doc for the kernel and fix indentation.

2019-04-12 15:29 UTC, oleg-h2o commented on chtest.c
> +if (B_size > 0)
Your indentation below this point is awful. It's almost impossible to read this code.

2019-04-17 16:02 UTC, oleg-h2o requested changes
Plz fix indentation ASAP.

2019-04-17 16:02 UTC, oleg-h2o commented on chtest.c
> + if(B_size==0){
It make almost impossible to read the file with these indentations.

2019-04-23 15:56 UTC, merged