Lesson 1: Task1: Simple guess number game
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #112
Opened 2019-04-10 14:37 UTC by VladFear

This PR is needed for adding simple guess game, which is very interesting and elaborating.

2019-04-11 15:37 UTC, galkinletter requested changes
Fix empty line

2019-04-11 15:37 UTC, galkinletter commented on 01-Git_Bash_Make/guess_a_number.sh
> +fi
add empty line at the end of file
```suggestion
fi

```

2019-04-12 11:53 UTC, VladFear commented
@galkinletter 
The code was rewritten from Bash to C++. Check it please.

2019-04-15 15:02 UTC, StanislavGoncharovGL commented on 01-Git_Bash_Make/main.cpp
> +	cout << "Enter value: ";
I think It is better to move the line output `cout << "Enter value: "` to the next commit, because functionality it is close to the 2nd commit.

2019-04-15 20:30 UTC, VladFear commented
@StanislavGoncharovGL 
Changes have been done. Please have a look.

2019-04-16 07:23 UTC, StanislavGoncharovGL commented
> @StanislavGoncharovGL
> Changes have been done. Please have a look.

Looks Ok, tnx

2019-04-16 07:53 UTC, VladFear commented
@StanislavGoncharovGL 
Can PR be merged?

2019-04-16 10:50 UTC, merged