Lesson 5-7: Driver for character device
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #116
Opened 2019-04-11 13:46 UTC by D-Alexandr

Added Makefile and driver for character device.

@oleg-h2o , @galkinletter please check my homework

2019-04-11 16:37 UTC, galkinletter requested changes
Please do it error handling for some events

Think of fatal errors and their handling.

2019-04-11 16:37 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/chrdev_driver.c
> +	if (cdev_add(cdev, dev, chrdev_nr_devs)) {
```suggestion
	if (cdev_add(cdev, dev, chrdev_nr_devs)) { 
			printk(KERN_WARNING "chrdev: cdev_add error \n");
		}
		printk(KERN_INFO "chrdev: %d:%d \n", chrdev_major, chrdev_minor);
	
```

printk(KERN_WARNING  "chrdev: cdev_add error \n");

Please do it error handling  for this.

Think of fatal errors and their handling.

2019-04-11 17:23 UTC, D-Alexandr commented
Fixed. @galkinletter  please check

2019-04-11 17:44 UTC, galkinletter requested changes
Think about freeing up the required resources after errors

2019-04-11 17:44 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/chrdev_driver.c
> +		printk(KERN_ERR "chrdev: chrdev_buffer is out of memory");
```suggestion
		printk(KERN_ERR "chrdev: chrdev_buffer is out of memory");
```
Think about freeing up the required resources after errors

2019-04-11 17:44 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/chrdev_driver.c
> +		goto fail;
```suggestion
		goto fail; 
```
Think about freeing up the required resources after errors

2019-04-11 17:45 UTC, galkinletter commented
Think about freeing up the required resources after errors

2019-04-17 15:58 UTC, oleg-h2o requested changes
Pl fix issues with indentation (checkpatch or whatever...)

2019-04-17 15:58 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/chrdev_driver.c
> +    sscanf(buf, "%d", &clean_flag);
Here're issues with indentation.

2019-04-23 16:08 UTC, galkinletter commented
fixed is correct

2019-04-23 16:08 UTC, merged