Lesson 7 Part 1: Character device driver
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #117
Opened 2019-04-11 17:37 UTC by Ayrum1158

2019-04-17 15:55 UTC, oleg-h2o requested changes
It's almost OK.

2019-04-17 15:55 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/character_driver.c
> +	int res_len = sprintf(res, "Buffer info:\n\tallocated size - %d bytes\n\tused size - %d bytes\n", alloc_size, used_size);
A very long line.

2019-04-17 15:55 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/character_driver.c
> +	cdev_add(&dev_struct, dev_num, NUMBER_OF_DEVICES);
cdev_add() can return an error. Plz handle it.

2019-05-07 16:16 UTC, oleg-h2o requested changes
Plz add if statement.

2019-05-07 16:16 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/character_driver.c
> +
if (err..) goto cdev_add_err ????

2019-05-07 16:20 UTC, galkinletter requested changes
Please fix

2019-05-07 16:20 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/chdev_test.script
> +echo "Testing done"
```suggestion
echo "Testing done"

```

Please, add empty line at the end of file

2019-05-11 12:28 UTC, Ayrum1158 commented
Added empty line to the end of the chdev_test.script and "if(err < 0) goto chdev_add_err;" to character_driver.c

2019-05-31 14:32 UTC, galkinletter commented
Ok

2019-05-31 14:32 UTC, merged