Lesson5-7: Character Device
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #122
Opened 2019-04-12 08:51 UTC by daaaanil81

Implement a character device driver for text messaging between users.

1. Implement a character device driver with the following requirements:
- 1kB buffer size;
- buffer increase as a module parameter ;
- should be available for all users;
- works only ASCII strings.

2.  Add the interfaces into the driver:
- sysfs for buffer clean up;
- procfs for displaying used buffer volume and buffer size

Bash script will be later. 
@galkinletter Check please my task.

2019-04-17 15:35 UTC, oleg-h2o requested changes
Plz make those minor fixes.

2019-04-17 15:35 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/moduleCharDev.c
> +    memset(dev_buffer, 0, all_memory);
Use kzalloc() to allocate memory. The memory is set to zero.

2019-04-17 15:35 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/moduleCharDev.c
> +        memset(dev_buffer, 0, all_memory);
Use kzfree() to wipe memory

2019-04-17 15:35 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/moduleCharDev.c
> +        if (time < 33 || time > 126) {
Why space is disabled here? ASCII 32=SPACE

2019-05-07 16:12 UTC, galkinletter requested changes
Please fix

2019-05-09 10:37 UTC, daaaanil81 commented
@galkinletter @oleg-h2o Check please my task.

2019-05-31 14:36 UTC, galkinletter commented
Please Bash script to do it  also. .

2019-05-31 14:37 UTC, galkinletter commented
Driver is OK. Bugs is fixed

2019-05-31 14:37 UTC, merged