Daniel.shami
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #123
Opened 2019-04-13 15:46 UTC by danismi715

- Create Makefile and initial driver code
- Add sysfs interface
- Add dev interface
- Add procfs interface
- Add entry point for module

Please, check my driver code. 
Thank you!

2019-04-17 15:24 UTC, oleg-h2o requested changes
Plz use checkpatch (or indent) to fix indentation.

2019-04-17 15:24 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/my_chardev.c
> +	char data_buff[10];
10 bytes is not enough here: int value may require up to 9 decimal digits, but you've added in the proc_read() 2 more characters (a whitespace and \n).

2019-04-17 15:24 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/my_chardev.c
> +    if( length < len ) return -EINVAL;
Code indentation is broken here.

2019-04-20 12:50 UTC, danismi715 commented
- Expanded output buffer for procfs and fixed indents

2019-04-23 16:09 UTC, galkinletter commented
fixed is correct

2019-04-23 16:09 UTC, merged