Lesson 7: Character driver
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #126
Opened 2019-04-20 14:43 UTC by Noxybot

2019-04-23 16:34 UTC, galkinletter requested changes
Need fix

2019-04-23 16:34 UTC, galkinletter commented on 02-KernelModules_CharacterDevice/Makefile
> +KDIR := /home/eduard/Kernel_i386
```suggestion
KDIR := /home/eduard/Kernel_i386
```
$KDIR refers to the path of the kernel source directory

Please use variable  as path

No hardcoded paths!

2019-04-23 16:35 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/character_driver.c
> +#define NUMBER_OF_DEVICES   1
Plz move all #define(s) to the upper part of this file.

2019-04-23 16:35 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/character_driver.c
> +#define PROC_DIR_NAME    "My_proc_stats"
.. and these ones also...

2019-04-23 16:35 UTC, oleg-h2o commented on 02-KernelModules_CharacterDevice/character_driver.c
> +#define SYS_DIR_NAME    "My_sys_operations"
... and these.

2019-04-23 17:01 UTC, galkinletter commented
No hardcoded paths! Please fix also

2019-04-24 15:42 UTC, galkinletter commented
Ok

2019-04-24 15:42 UTC, merged