Practice 1 MPU6050
Kernel-GL-HRK/gl-kernel-basecamp-2019 pull request #144
Opened 2019-05-08 22:23 UTC by D-Alexandr

Added first part practice 1 mpu6050. Script communicates to mpu6050 by i2c and display value temperature on Celsius and Fahrenheit

2019-05-10 11:14 UTC, yekovalyov requested changes

2019-05-10 11:14 UTC, yekovalyov commented on 04-mpu6050/scripts/mpu6050_temp.sh
>      temp_c=$(echo " scale = 2; $temp_sig / 340 + 36.53" | bc)
Required resolution is 0.001. scale=2 provides only resolution 0.01

2019-05-10 11:14 UTC, yekovalyov commented on 04-mpu6050/scripts/mpu6050_temp.sh
> +    temp_f=$(echo " scale = 2; (9/5 * $temp_c) + 32" | bc)
Required resolution is 0.001. scale=2 provides only resolution 0.01

2019-05-10 11:28 UTC, D-Alexandr commented
mpu6050 sensitivity to temperature ±1/С°. Why do we need measurements with an accuracy of 0.001?

2019-05-10 11:55 UTC, yekovalyov commented
> mpu6050 sensitivity to temperature ±1/С°. Why do we need measurements with an accuracy of 0.001?

Please read task and driver docs.

2019-05-12 23:59 UTC, yekovalyov requested changes
Issues in script implementation were addressed.
Only skeleton of module was implemented.

2019-05-22 12:15 UTC, yekovalyov requested changes

2019-05-22 12:15 UTC, yekovalyov commented on 04-mpu6050/module/mpu6050.c
> +	sprintf(buf, "%d.%03d\n", g_mpu6050_data.temperature / shift_number, g_mpu6050_data.temperature % shift_number);
Please check your code style using script from Linux repository.
scripts/checkpatch.pl --no-tree -f *.c

2019-05-27 15:00 UTC, yekovalyov approved these changes

2019-05-27 15:00 UTC, merged